---
- name: Copy fail2ban iptables config file
  ansible.builtin.template:
    src: iptables-ipset-allports.conf.j2
    dest: /etc/fail2ban/action.d/iptables-ipset-allports.conf
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart fail2ban service

- name: Copy fail2ban locale config file(s)
  ansible.builtin.template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart fail2ban service

- name: Copy fail2ban jail locale config file
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart fail2ban service
