---
- name: Update repo cache and install fail2ban with ipset packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - fail2ban
    - ipset
  notify:
    - Enable fail2ban service
    - Restart fail2ban service
