---
- name: Include ./install.yml
  ansible.builtin.import_tasks: install.yml
  tags:
    - install_fail2ban
    - install

- name: Include ./configure.yml
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configure_fail2ban
    - configure
